[platformio]
# Tell PlatformIO where the sketch is located
src_dir = arduino-greenhouse-controller

[env:uno]
platform = atmelavr
board = uno
framework = arduino

[env:esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

# PlatformIO will automatically download these libraries
# (Arduino IDE users will just install them via the Library Manager as usual)
lib_deps = 
    robtillaart/DHTstable @ ^1.1.1
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    adafruit/RTClib @ ^2.1.3